### Criar um novo pedido
POST http://localhost:8080/pedidos
Content-Type: application/json

{
  "descricao": "mesa de Erick",
  "valorTotal": 30,
  "status": true
}

### Listar todos os pedidos
GET http://localhost:8080/pedidos

### Buscar um pedido específico pelo ID
GET http://localhost:8080/pedidos/1

### Deletar um pedido pelo ID
DELETE http://localhost:8080/pedidos/1

